apiVersion: v1
kind: Service
metadata:
  name: fuze-frontend
  namespace: fuze-ai-paas
  labels:
    app: fuze-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
    protocol: TCP
    name: http
  selector:
    app: fuze-frontend
